# Site settings
title: "Gordon Brown on<br>C++, Gamedev, Heterogeneous Computing"
author: "Gordon Brown"
description: "This is a programming blog about C++, gamedev, and heterogeneous computing."
keywords: "C++, Templates, Gamedev, Heterogeneous"
biography: "I am a software developer at <a href='http://www.codeplay.com'>Codeplay Software</a>, where I work on SYCL; an open standard C++ programming model for heterogeneous systems. I am an active contributor to the SYCL and the C++ standards. I am a C++ and game dev enthusiast."
colophon: "This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>.<br>Theme was created by Hugo Sereno Ferreira."

baseurl: ""
url: "https://aerialmantis.github.io"

twitter_username: aerialmantis
github_username: aerialmantis
linkedin_username: 
facebook_username: gordonb589
google-analytics: UA-89931397-1

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
